jmeterservice:
  image:
    repository: docker.io/keptn/jmeter-service # Container Image Name
    pullPolicy: IfNotPresent                   # Kubernetes Image Pull Policy
    tag: ""                                    # Container Tag
  service:
    enabled: true                              # Creates a Kubernetes Service for the jmeter-service
  gracePeriod: 60                              # PreStop hook time +30s
  preStopHookTime: 5
  resources:                                   # Resource limits and requests
    requests:
      cpu: "100m"
      memory: "128Mi"
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you want to limit the resources, you can uncomment the following lines
# but be aware that JMeter needs  lots of resources while running load tests.
#    limits:
#      cpu: "2"
#      memory: "2Gi"

distributor:
  stageFilter: ""                            # Sets the stage this helm service belongs to
  serviceFilter: ""                          # Sets the service this helm service belongs to
  projectFilter: ""                          # Sets the project this helm service belongs to
  image:
    repository: docker.io/keptn/distributor  # Container Image Name
    pullPolicy: IfNotPresent                 # Kubernetes Image Pull Policy
    tag: ""                                  # Container Tag
  config:
    queueGroup:
      enabled: true                          # Enable connection via Nats queue group to support exactly-once message processing
    oauth:
      clientID: ""
      clientSecret: ""
      discovery: ""
      tokenURL: ""
      scopes: ""
  resources:                                 # Resource limits and requests
    requests:
      memory: "16Mi"
      cpu: "25m"
    limits:
      memory: "32Mi"
      cpu: "100m"

remoteControlPlane:
  enabled: false                             # Enables remote execution plane mode
  api:
    protocol: "https"                        # Used Protocol (http, https)
    hostname: ""                             # Hostname of the control plane cluster (and Port)
    apiValidateTls: true                     # Defines if the control plane certificate should be validated
    token: ""                                # Keptn API Token
    tokenSecretName:                         # Use a predefined secret ie: from sealed-secrets. Must have a config key of keptn-api-token inside the secret

imagePullSecrets: []                         # Secrets to use for container registry credentials

serviceAccount:
  create: true                               # Enables the service account creation
  annotations: {}                            # Annotations to add to the service account
  name: ""                                   # The name of the service account to use.

podAnnotations: {}                           # Annotations to add to the created pods

podSecurityContext: {}                       # Set the pod security context (e.g. fsGroups)
  # fsGroup: 2000

securityContext: {}                          # Set the security context (e.g. runAsUser)
#  readOnlyRootFilesystem: true
#  runAsNonRoot: true
#  runAsUser: 1000

nodeSelector: {}                                # Node selector configuration

tolerations: []                                 # Tolerations for the pods

affinity: {}                                    # Affinity rules

logLevel: info
