apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodata
  labels:
    app.kubernetes.io/name: mongodata
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: keptn
    app.kubernetes.io/component: {{ include "mongodb.name" . }}
    helm.sh/chart: {{ include "mongodb.chart" . }}    
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
