version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: "wednesday"
    open-pull-requests-limit: 5
    rebase-strategy: "disabled"
    commit-message:
      prefix: build
      include: scope

  - package-ecosystem: gomod
    directory: "/approval-service"
    schedule:
      interval: weekly
      day: "wednesday"
    open-pull-requests-limit: 4
    rebase-strategy: "disabled"
    commit-message:
      prefix: build
      include: scope

  - package-ecosystem: gomod
    directory: "/cli"
    schedule:
      interval: weekly
      day: "wednesday"
    open-pull-requests-limit: 4
    rebase-strategy: "disabled"
    commit-message:
      prefix: build
      include: scope

  - package-ecosystem: gomod
    directory: "/api"
    schedule:
      interval: weekly
      day: "wednesday"
    open-pull-requests-limit: 4
    rebase-strategy: "disabled"
    commit-message:
      prefix: build
      include: scope

  - package-ecosystem: gomod
    directory: "/distributor"
    schedule:
      interval: weekly
      day: "wednesday"
    open-pull-requests-limit: 4
    rebase-strategy: "disabled"
    commit-message:
      prefix: build
      include: scope

  - package-ecosystem: gomod
    directory: "/configuration-service"
    schedule:
      interval: weekly
      day: "wednesday"
    open-pull-requests-limit: 4
    rebase-strategy: "disabled"
    commit-message:
      prefix: build
      include: scope

  - package-ecosystem: gomod
    directory: "/helm-service"
    schedule:
      interval: weekly
      day: "wednesday"
    open-pull-requests-limit: 4
    rebase-strategy: "disabled"
    commit-message:
      prefix: build
      include: scope

  - package-ecosystem: gomod
    directory: "/jmeter-service"
    schedule:
      interval: weekly
      day: "wednesday"
    open-pull-requests-limit: 4
    rebase-strategy: "disabled"
    commit-message:
      prefix: build
      include: scope

  - package-ecosystem: gomod
    directory: "/lighthouse-service"
    schedule:
      interval: weekly
      day: "wednesday"
    open-pull-requests-limit: 4
    rebase-strategy: "disabled"
    commit-message:
      prefix: build
      include: scope

  - package-ecosystem: gomod
    directory: "/mongodb-datastore"
    schedule:
      interval: weekly
      day: "wednesday"
    open-pull-requests-limit: 4
    rebase-strategy: "disabled"
    commit-message:
      prefix: build
      include: scope

  - package-ecosystem: gomod
    directory: "/platform-support/openshift-route-service"
    schedule:
      interval: weekly
      day: "wednesday"
    open-pull-requests-limit: 4
    rebase-strategy: "disabled"
    commit-message:
      prefix: build
      include: scope

  - package-ecosystem: gomod
    directory: "/remediation-service"
    schedule:
      interval: weekly
      day: "wednesday"
    open-pull-requests-limit: 4
    rebase-strategy: "disabled"
    commit-message:
      prefix: build
      include: scope

  - package-ecosystem: gomod
    directory: "/secret-service"
    schedule:
      interval: weekly
      day: "wednesday"
    open-pull-requests-limit: 4
    rebase-strategy: "disabled"
    commit-message:
      prefix: build
      include: scope

  - package-ecosystem: gomod
    directory: "/shipyard-controller"
    schedule:
      interval: weekly
      day: "wednesday"
    open-pull-requests-limit: 4
    rebase-strategy: "disabled"
    commit-message:
      prefix: build
      include: scope

  - package-ecosystem: gomod
    directory: "/statistics-service"
    schedule:
      interval: weekly
      day: "wednesday"
    open-pull-requests-limit: 4
    rebase-strategy: "disabled"
    commit-message:
      prefix: build
      include: scope

  - package-ecosystem: npm
    directory: "/bridge"
    schedule:
      interval: weekly
      day: "wednesday"
    commit-message:
      prefix: build
      include: scope

  - package-ecosystem: npm
    directory: "/bridge/server"
    schedule:
      interval: weekly
      day: "wednesday"
    commit-message:
      prefix: build
      include: scope
