apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-datastore
  namespace: keptn-datastore
  annotations:
    fluentbit.io/exclude: "true"
spec:
  selector:
    matchLabels:
      run: mongodb-datastore
  replicas: 1
  template:
    metadata:
      labels:
        run: mongodb-datastore
    spec:
      containers:
      - name: mongodb-datastore
        image: keptn/mongodb-datastore:0.5.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: MONGO_DB_CONNECTION_STRING
          value: 'mongodb://user:password@mongodb:27017/keptn'
        - name: MONGO_DB_NAME
          value: 'keptn'
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-datastore
  namespace: keptn-datastore
  labels:
    run: mongodb-datastore
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: mongodb-datastore