apiVersion: v2
name: keptn
description: Cloud-native application life-cycle orchestration

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: latest

home: "https://keptn.sh"
icon: "https://raw.githubusercontent.com/cncf/artwork/master/projects/keptn/icon/color/keptn-icon-color.svg"
sources:
  - "https://github.com/keptn/keptn"
  - "https://github.com/keptn/helm-charts"
annotations:
  artifacthub.io/license: "Apache-2.0"
  artifacthub.io/links: |
    - name: support
      url: https://github.com/keptn/keptn/issues
keywords:
  - cloud-native
  - orchestration
  - cd
  - keptn

dependencies:
  - name: mongodb
    version: 11.2.0
    repository: https://charts.bitnami.com/bitnami
    condition: mongo.enabled
    alias: mongo
  - name: nats
    version: 0.13.2
    repository: https://nats-io.github.io/k8s/helm/charts/
