---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api
  namespace: keptn
spec:
  hosts:
    - "api.keptn.DOMAIN_PLACEHOLDER"
  gateways:
    - public-gateway.istio-system
  http:
    - route:
        - destination:
            host: api-gateway-nginx.keptn.svc.cluster.local
      websocketUpgrade: true
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: api-gateway-nginx
  namespace: keptn
spec:
  host: api-gateway-nginx.keptn.svc.cluster.local
