---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openshift-route-service
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: openshift-route-service
  replicas: 1
  template:
    metadata:
      labels:
        run: openshift-route-service
    spec:
      containers:
      - name: openshift-route-service
        image: keptn/openshift-route-service:0.6.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: APP_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: keptn-domain
              key: app_domain
---
apiVersion: v1
kind: Service
metadata:
  name: openshift-route-service
  namespace: keptn
  labels:
    run: openshift-route-service
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: openshift-route-service
