apiVersion: eventing.knative.dev/v1alpha1
kind: Channel
metadata:
  name: start-tests
  namespace: keptn
spec:
  provisioner:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: ClusterChannelProvisioner
    name: in-memory-channel