---
swagger: '2.0'
info:
  title: mongodb-datastore
  version: develop
basePath: /
consumes:
  - application/cloudevents+json
  - application/json
produces:
  - application/cloudevents+json
  - application/json
paths:
  /event:
    post:
      tags:
        - event
      operationId: saveEvent
      summary: Saves an event to the datastore
      parameters:
        - name: body
          in: body
          schema:
            "$ref": "#/definitions/KeptnContextExtendedCE"
      responses:
        201:
          description: created
        default:
          description: error
          schema:
            "$ref": "#/definitions/error"
    get:
      tags:
        - event
      operationId: getEvents
      summary: Gets events from the data store
      parameters:
        - name: keptnContext
          in: query
          type: string
          required: false
          description: keptnContext of the events to get
        - name: type
          in: query
          type: string
          required: false
          description: Type of the keptn cloud event
        - name: fromTime
          in: query
          type: string
          required: false
          description: From time to fetch keptn cloud events
        - name: root
          in: query
          type: string
          required: false
          description: Set to load only root events
        - name: project
          in: query
          type: string
          required: false
          description: Name of the project
        - name: stage
          in: query
          type: string
          required: false
          description: Name of the stage
        - name: service
          in: query
          type: string
          required: false
          description: Name of the service
        - name: eventID
          in: query
          type: string
          required: false
          description: EventID
        - name: source
          in: query
          type: string
          required: false
          description: Name of the event source
        - "$ref": "#/parameters/pagesizeParam"
        - "$ref": "#/parameters/pageParam"
      responses:
        200:
          description: ok
          schema:
            type: object
            properties:
              nextPageKey:
                type: string
                description: Pointer to the next page
              totalCount:
                type: integer
                description: Total number of events
              pageSize:
                type: integer
                description: Size of the returned page
              events:
                type: array
                items:
                  "$ref": "#/definitions/KeptnContextExtendedCE"
        default:
          description: error
          schema:
            "$ref": "#/definitions/error"

  /event/type/{eventType}:
    parameters:
      - name: eventType
        in: path
        type: string
        required: true
    get:
      tags:
        - event
      operationId: getEventsByType
      summary: Gets events by their type from the mongodb
      parameters:
        - name: filter
          in: query
          type: string
        - name: excludeInvalidated
          in: query
          type: boolean
        - name: fromTime
          in: query
          type: string
          required: false
        - "$ref": "#/parameters/pagesizeParam"
        - "$ref": "#/parameters/pageParam"
      responses:
        200:
          description: ok
          schema:
            type: object
            properties:
              nextPageKey:
                type: string
                description: Pointer to the next page
              totalCount:
                type: integer
                description: Total number of events
              pageSize:
                type: integer
                description: Size of the returned page
              events:
                type: array
                items:
                  "$ref": "#/definitions/KeptnContextExtendedCE"
        default:
          description: error
          schema:
            "$ref": "#/definitions/error"


parameters:
  pagesizeParam:
    name: pageSize
    in: query
    type: integer
    required: false
    default: 20
    minimum: 1
    maximum: 100
    description: Page size to be returned
  pageParam:
    name: nextPageKey
    in: query
    type: string
    required: false
    description: Key of the page to be returned
definitions:
  KeptnContextExtendedCE:
    allOf:
      - "$ref": https://raw.githubusercontent.com/cloudevents/spec/v0.2/spec.json#/definitions/event
      - type: object
        properties:
          shkeptncontext:
            type: string
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
      fields:
        type: string
  principal:
    type: string
