---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-openshift-route-service
  namespace: keptn
  labels:
    "app": "keptn"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-create-delete-route
  namespace: keptn
  labels:
    "app": "keptn"
rules:
  - apiGroups:
      - ""
      - route.openshift.io
    resources:
      - routes
      - routes/custom-host
    verbs:
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-create-delete-route
  namespace: keptn
  labels:
    "app": "keptn"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-create-delete-route
subjects:
  - kind: ServiceAccount
    name: keptn-openshift-route-service
    namespace: keptn
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-create-route
  namespace: istio-system
  labels:
    "app": "keptn"
rules:
  - apiGroups:
      - ""
      - route.openshift.io
    resources:
      - routes
      - routes/custom-host
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-create-route
  namespace: istio-system
  labels:
    "app": "keptn"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-create-route
subjects:
  - kind: ServiceAccount
    name: keptn-openshift-route-service
    namespace: keptn
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptn-secuirtycontextconstraints
  labels:
    "app": "keptn"
rules:
  - apiGroups:
      - ""
      - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - get
      - update
    resourceNames:
      - privileged
      - anyuid
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keptn-secuirtycontextconstraints
  labels:
    "app": "keptn"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keptn-secuirtycontextconstraints
subjects:
  - kind: ServiceAccount
    name: keptn-openshift-route-service
    namespace: keptn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openshift-route-service
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: openshift-route-service
  replicas: 1
  template:
    metadata:
      labels:
        run: openshift-route-service
    spec:
      serviceAccountName: keptn-openshift-route-service
      containers:
      - name: openshift-route-service
        image: keptn/openshift-route-service:latest
        ports:
        - containerPort: 8080
        - containerPort: 8081
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: BRIDGE_PORT
          value: '3000'
        - name: INGRESS_HOSTNAME_SUFFIX
          valueFrom:
            configMapKeyRef:
              name: ingress-config
              key: ingress_hostname_suffix
        - name: INGRESS_PROTOCOL
          valueFrom:
            configMapKeyRef:
              name: ingress-config
              key: ingress_protocol
        - name: INGRESS_PORT
          valueFrom:
            configMapKeyRef:
              name: ingress-config
              key: ingress_port
---
apiVersion: v1
kind: Service
metadata:
  name: openshift-route-service
  namespace: keptn
  labels:
    run: openshift-route-service
spec:
  ports:
  - name: cloudevents
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: expose-bridge
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    run: openshift-route-service
