---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-datastore
  namespace: keptn
  annotations:
    fluentbit.io/exclude: "true"
  labels:
    app.kubernetes.io/name: mongodb-datastore
    app.kubernetes.io/instance: keptn
    app.kubernetes.io/part-of: keptn-keptn
    app.kubernetes.io/component: keptn
    app.kubernetes.io/version: develop
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mongodb-datastore
      app.kubernetes.io/instance: keptn
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongodb-datastore
        app.kubernetes.io/instance: keptn
        app.kubernetes.io/part-of: keptn-keptn
        app.kubernetes.io/component: keptn
        app.kubernetes.io/version: develop
    spec:
      serviceAccountName: keptn-default
      containers:
      - name: mongodb-datastore
        image: keptndev/mongodb-datastore:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "32Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: DT_CUSTOM_PROP
          value: 'keptn_service=mongodb-datastore'
        - name: PREFIX_PATH
          value: ""
        - name: MONGODB_HOST
          value: 'keptn-mongo:27017'
        - name: MONGODB_DATABASE
          value: 'keptn'
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: mongodb-user
        - name: MONGODB_PASSWORD
          valueFrom:
              secretKeyRef:
                name: mongodb-credentials
                key: mongodb-passwords
        - name: NATS_URL
          value: 'nats://keptn-nats'
        - name: K8S_NAMESPACE
          value: keptn
        - name: K8S_DEPLOYMENT_NAME
          value: mongodb-datastore
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-datastore
  namespace: keptn
  labels:
    app.kubernetes.io/name: mongodb-datastore
    app.kubernetes.io/instance: keptn
    app.kubernetes.io/part-of: keptn-keptn
    app.kubernetes.io/component: keptn
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app.kubernetes.io/name: mongodb-datastore
    app.kubernetes.io/instance: keptn
