apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: docker-registry
  namespace: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      service: dockerregistry
  template:
    metadata:
      labels:
        service: dockerregistry
    spec:
      containers:
      - name: registry
        image: registry:2
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
        volumeMounts:
              - name: docker-registry-persistent-storage
                mountPath: /var/lib/registry
      volumes:
      - name: docker-registry-persistent-storage
        persistentVolumeClaim:
           claimName: docker-registry