apiVersion: batch/v1
kind: Job
metadata:
  name: installer
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: installer
    spec:
      volumes:
      - name: kubectl
        emptyDir: {}
      containers:
      - name: keptn-installer
        image: keptn/installer:dcb635e
        env:       
        - name: PLATFORM
          value: PLATFORM_PLACEHOLDER
        - name: GATEWAY_TYPE
          value: GATEWAY_TYPE_PLACEHOLDER
        - name: INGRESS
          value: INGRESS_PLACEHOLDER
        - name: USE_CASE
          value: USE_CASE_PLACEHOLDER
      restartPolicy: Never
