{{- if .Values.webhookService.enabled }}
# webhook-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-service
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: webhook-service
spec:
  selector:
    matchLabels: {{- include "common.labels.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: webhook-service
  replicas: 1
  {{- include "keptn.common.update-strategy" . | nindent 2 }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
        app.kubernetes.io/component: webhook-service
    spec:
      {{- include "keptn.common.pod-security-context" . | nindent 6 }}
      serviceAccountName: keptn-webhook-service
      containers:
        - name: webhook-service
          image: {{ .Values.webhookService.image.repository }}:{{ .Values.webhookService.image.tag | default .Chart.AppVersion }}
          {{- $prestop := .Values.webhookService.preStopHookTime | default 20 | quote -}}
          {{- include "keptn.prestop" $prestop | nindent 10 }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.webhookService.resources | nindent 12 }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LOG_LEVEL
              value: {{ .Values.logLevel | default "info" }}
            {{- include "keptn.common.env.vars" . | nindent 12 }}
          {{- include "keptn.common.container-security-context" . | nindent 10 }}
          {{- if .Values.webhookService.extraVolumeMounts }}
          volumeMounts:
          {{- include "common.tplvalues.render" ( dict "value" .Values.webhookService.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
        {{- with .Values.webhookService.sidecars }}
        {{- include "common.tplvalues.render" ( dict "value" . "context" $ ) | nindent 8 }}
        {{- end }}
      {{- if .Values.webhookService.extraVolumes }}
      volumes:
      {{- include "common.tplvalues.render" ( dict "value" .Values.webhookService.extraVolumes "context" $) | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.webhookService.gracePeriod | default 60 }}
      {{- include "keptn.nodeSelector" (dict "value" .Values.webhookService.nodeSelector "default" .Values.nodeSelector "indent" 6 "context" . )}}
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: webhook-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector: {{- include "common.labels.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: webhook-service
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keptn-webhook-config
  labels:
    app.kubernetes.io/name: webhook-service-config
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: webhook-service
    helm.sh/chart: {{ include "keptn.chart" . }}
data:
  denyList: |-
    kubernetes
    kubernetes.default
    kubernetes.default.svc
    kubernetes.default.svc.cluster.local
    svc.cluster.local
    cluster.local
    localhost
    127.0.0.1
    ::1
