apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: control
  namespace: keptn
spec:
  runLatest:
    configuration:
      build:
        apiVersion: build.knative.dev/v1alpha1
        kind: Build
        metadata:
          name: control-builder
          namespace: keptn
        spec:
          serviceAccountName: build-bot
          source:
            git:
              url: https://github.com/keptn/keptn.git
              revision: auth-component
          template:
            name: kaniko
            arguments:
              - name: IMAGE
                value: docker-registry.cicd.svc.cluster.local:5000/keptn/keptn-control:latest
              - name: DOCKERFILE
                value: /core/control/Dockerfile
      revisionTemplate:
        metadata:
        spec:
          container:
            image: REGISTRY_URI_PLACEHOLDER:5000/keptn/keptn-control:latest
            imagePullPolicy: Always
