---
apiVersion: v1
kind: Service
metadata:
  name: ansible-tower
  labels:
    app: ansible-tower
  namespace: tower
spec:
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  selector:
    app: ansible-tower
  type: LoadBalancer