dist: xenial
language: bash
os: linux
services:
  - docker
env:
  global:
    - IMAGE=keptncontrib/jmeter-extended-service
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org
before_install:
  - export REPO_URL="$(git remote get-url --all origin)"
  # get some git meta data like branch name, latest tag etc...
  - GIT_LAST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1) || echo "0.0.0")
  - GIT_BRANCH_NAME=$(git branch | grep \* | cut -d ' ' -f2)
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - export BRANCH_SLUG=$(echo $BRANCH | iconv -t ascii//TRANSLIT | sed -r s/[^a-zA-Z0-9]+/-/g | sed -r s/^-+\|-+$//g | tr A-Z a-z)
  - export GIT_SHA=$(git rev-parse --short HEAD)
  # Build version string
  - |
    if [[ "$BRANCH" == "release-"* ]]; then
      # extract version from branch name
      VERSION=${BRANCH#"release-"}
    else
      if [[ "$BRANCH" == "$TRAVIS_TAG" ]]; then
        # use tag as version
        VERSION="${TRAVIS_TAG}"
      else
        # Development Branch - use last tag with branch name
        VERSION="${GIT_LAST_TAG}-${BRANCH_SLUG}"
      fi
    fi
  - export VERSION
  - export DATE="$(date +'%Y%m%d')"
  - export TIME="$(date +'%H%M')"
  # write a manifest file
  - ./docker/writeManifest.sh
  - cat ./docker/MANIFEST
  # uncomment certain lines from Dockerfile that are for travis builds only
  - sed -i '/#travis-uncomment/s/^#travis-uncomment //g' Dockerfile
jobs:
  include:
    - stage: Build Images (all branches)
      script:
        - docker build . -t "${IMAGE}:${GIT_SHA}" --build-arg version=${VERSION} || travis_terminate -1
        - docker tag "${IMAGE}:${GIT_SHA}" "${IMAGE}:${VERSION}"
        - docker tag "${IMAGE}:${GIT_SHA}" "${IMAGE}:${VERSION}-${DATE}"
        - docker tag "${IMAGE}:${GIT_SHA}" "${IMAGE}:${VERSION}-${DATE}.${TIME}"
      before_deploy:
        - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD"
      deploy:
        provider: script
        script: docker push "${IMAGE}"
        on:
          all_branches: true
      after_deploy:
        - echo "The following images have been built (and pushed to dockerhub):"
        - docker images | grep "${IMAGE}"
