openshift:
  enabled: false

ingressConfig:
  ingress_hostname_suffix: "svc.cluster.local"
  ingress_protocol: "http"
  ingress_port: "80"
  istio_gateway: "public-gateway.istio-system"

distributor:
  image:
    repository: docker.io/keptn/distributor

jmeterService:
  image:
    repository: docker.io/keptn/jmeter-service

helmService:
  image:
    repository: docker.io/keptn/helm-service