# This secret is for development only and not used for a Keptn deployment.
# The user, password, and admin_password hold default MongoDB credentials.
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: keptn
  labels:
    app: mongodb-datastore
type: Opaque
data:
  user: dXNlcg==
  password: cGFzc3dvcmQ=
  admin_password: cGFzc3dvcmQ=
