---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: keptn
  labels:
    app: mongodb-datastore
type: Opaque
data:
  user: dXNlcg==
  password: cGFzc3dvcmQ=
  admin_password: cGFzc3dvcmQ=