name: Dependencies and Licenses
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  generate-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Core Repo
        uses: actions/checkout@v3
        with:
          path: 'keptn'

      - name: Checkout go-utils Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.KEPTN_BOT_TOKEN }}
          path: 'go-utils'
          repository: 'keptn/go-utils'

      - name: Checkout kubernetes-utils Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.KEPTN_BOT_TOKEN }}
          path: 'kubernetes-utils'
          repository: 'keptn/kubernetes-utils'

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Install go-licence-detector
        run: |
          go get go.elastic.co/go-licence-detector

      - name: Set up Node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16

      - name: Install npm libs
        run: |
          yarn global add license-report

      - name: GO dependencies and licenses
        run: ./keptn/gh-actions-scripts/dependencies-and-licenses.sh

      - name: Node dependencies and licenses
        run: |
          echo "ğŸ” Analyzing dependencies in module bridge"
          ( cd keptn/keptn/bridge || return ; license-report --only-prod --output=csv > ../../../dependencies-and-licenses-node.txt )

          echo
          echo "ğŸ‘ done. written results to ./dependencies-and-licenses-node.txt"

          cat dependencies-and-licenses-node.txt

      - name: Upload dependencies and licenses artifact
        uses: actions/upload-artifact@v3
        with:
          name: dependencies-and-licenses
          path: dependencies-and-licenses-*.txt
