name: Dependencies and Licenses
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  generate-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Core Repo
        uses: actions/checkout@v3
        with:
          path: 'keptn'

      - name: Checkout go-utils Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.KEPTN_BOT_TOKEN }}
          path: 'go-utils'
          repository: 'keptn/go-utils'

      - name: Checkout kubernetes-utils Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.KEPTN_BOT_TOKEN }}
          path: 'kubernetes-utils'
          repository: 'keptn/kubernetes-utils'

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Install go-licence-detector
        run: |
          go get go.elastic.co/go-licence-detector

      - name: Set up Node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16

      - name: Install npm libs
        run: |
          yarn global add license-report synp

      - name: GO dependencies and licenses
        run: |
          TMP_DIR=$(mktemp -d 2>/dev/null || mktemp -d -t 'keptndeps')
          MODULES=(
            api
            approval-service
            cli
            configuration-service
            distributor
            go-sdk
            helm-service
            jmeter-service
            lighthouse-service
            mongodb-datastore
            remediation-service
            secret-service
            shipyard-controller
            statistics-service
            webhook-service
            resource-service
          )
          
          cd ./keptn || return
          
          for MODULE in "${MODULES[@]}"; do
            echo "ğŸ” Analyzing dependencies in module $MODULE"
            cd ./"$MODULE" || return
            go mod tidy
            go list -m -json all | \
              go-licence-detector \
                -depsTemplate=../.dependencies/templates/dependencies.csv.tmpl \
                -depsOut="${TMP_DIR}"/"${MODULE}"-dependencies.txt \
                -overrides=../.dependencies/overrides/overrides.json
            cd ..
          done
          
          cd ..
          
          echo "ğŸ” Analyzing dependencies in go-utils"
          cd ./go-utils || return
          go mod tidy
          go list -m -json all | \
            go-licence-detector \
              -depsTemplate=../keptn/.dependencies/templates/dependencies.csv.tmpl \
              -depsOut="${TMP_DIR}"/go-utils-dependencies.txt
          cd ..
          
          echo "ğŸ” Analyzing dependencies in kubernetes-utils"
          cd ./kubernetes-utils || return
          go mod tidy
          go list -m -json all | \
            go-licence-detector \
              -depsTemplate=../keptn/.dependencies/templates/dependencies.csv.tmpl \
              -depsOut="${TMP_DIR}"/kubernetes-utils-dependencies.txt
          cd ..
          
          cat "$TMP_DIR"/*.txt | sort | uniq > dependencies-and-licenses-go.txt
          
          echo
          echo "ğŸ‘ done. written results to ./dependencies-and-licenses-go.txt"
          
          cat dependencies-and-licenses-go.txt

      - name: Node dependencies and licenses
        run: |
          echo "ğŸ” Analyzing dependencies in module bridge"
          cd ./keptn/bridge || return
          yarn install --frozen-lockfile
          synp --source-file ./yarn.lock
          license-report --only-prod --output=csv > ../../dependencies-and-licenses-node.txt
          cd ../..

          echo
          echo "ğŸ‘ done. written results to ./dependencies-and-licenses-node.txt"

          cat dependencies-and-licenses-node.txt

      - name: Upload dependencies and licenses artifact
        uses: actions/upload-artifact@v3
        with:
          name: dependencies-and-licenses
          path: dependencies-and-licenses-*.txt
