name: Dependencies and Licenses
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  generate-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Core Repo
        uses: actions/checkout@v2
        with:
          path: 'keptn/keptn'
      - name: Checkout go-utils Repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.KEPTN_BOT_TOKEN }}
          path: 'keptn/go-utils'
          repository: 'keptn/go-utils'
      - name: Checkout kubernetes-utils Repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.KEPTN_BOT_TOKEN }}
          path: 'keptn/kubernetes-utils'
          repository: 'keptn/kubernetes-utils'
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Install go-licence-detector
        run: |
          go get go.elastic.co/go-licence-detector
      - name: Set up Node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14
      - name: Install npm libs
        run: |
          npm install -g license-report
      - name: GO dependencies and licenses
        run: |
          TMP_DIR=$(mktemp -d 2>/dev/null || mktemp -d -t 'keptndeps')
          MODULES="api approval-service cli configuration-service distributor helm-service jmeter-service lighthouse-service mongodb-datastore remediation-service secret-service shipyard-controller statistics-service"
          for MODULE in $MODULES; do
             echo "ğŸ” Analyzing dependencies in module $MODULE"
             ( cd keptn/keptn/"$MODULE" || return ; go mod tidy > /dev/null 2>&1; go list -m -json all | go-licence-detector -depsTemplate=../.dependencies/templates/dependencies.csv.tmpl -depsOut="${TMP_DIR}"/"${MODULE}"-dependencies.txt  -overrides=../.dependencies/overrides/overrides.json )
          done

          echo "ğŸ” Analyzing dependencies in go-utils"
          ( cd keptn/go-utils || return ; go mod tidy > /dev/null 2>&1; go list -m -json all | go-licence-detector -depsTemplate=../keptn/.dependencies/templates/dependencies.csv.tmpl -depsOut="${TMP_DIR}"/go-utils-dependencies.txt )

          echo "ğŸ” Analyzing dependencies in kubernetes-utils"
          ( cd keptn/kubernetes-utils || return ; go mod tidy > /dev/null 2>&1; go list -m -json all | go-licence-detector -depsTemplate=../keptn/.dependencies/templates/dependencies.csv.tmpl -depsOut="${TMP_DIR}"/kubernetes-utils-dependencies.txt )

          cat "$TMP_DIR"/*.txt | sort | uniq > dependencies-and-licenses-go.txt

          echo
          echo "ğŸ‘ done. written results to ./dependencies-and-licenses-go.txt"

          cat dependencies-and-licenses-go.txt
      - name: Node dependencies and licenses
        run: |
          echo "ğŸ” Analyzing dependencies in module bridge"
          ( cd keptn/keptn/bridge || return ; license-report --only-prod --output=csv > ../../../dependencies-and-licenses-node.txt )

          echo
          echo "ğŸ‘ done. written results to ./dependencies-and-licenses-node.txt"

          cat dependencies-and-licenses-node.txt
      - name: Upload dependencies and licenses artifact
        uses: actions/upload-artifact@v2
        with:
          name: dependencies-and-licenses
          path: dependencies-and-licenses-*.txt
