name: Check deprecated K8s versions
on: [pull_request]
jobs:
  deprecated-version-check:
    name: deprecated version check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v2.3.4

      - name: check deprecated versions
        run: |
          ./gh-actions-scripts/install_helm.sh
          ./gh-actions-scripts/install_pluto.sh
          ./gh-actions-scripts/check_deprecated_versions.sh
