name: Detect Stale Images
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * 0'
jobs:
  cleanup:
    name: Detect Stale Images
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v2
      - name: Load CI Environemnt from .ci_env
        id: load_ci_env
        uses: c-py/action-dotenv-to-setenv@v3
        with:
          env-file: .ci_env
      - name: Detect stale images on DockerHub
        env:
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          DOCKER_ORG: ${{ env.DOCKER_ORGANIZATION }}
        run: ./gh-actions-scripts/detect_stale_images.sh
